//! Tests for the replay metadata `.ini` parser.
//!
//! The two fixtures below are verbatim copies of the sidecars from
//! `.sample-data/RBR/MINI JCW - Gabiria-Legazpi 2004/` (gitignored, per
//! PROJECT_PLAN.md's convention of not committing capture data). They're
//! inlined rather than referenced so the suite is hermetic and runs
//! anywhere. `parses_real_sample_data_when_present` additionally exercises
//! the on-disk path against the real captures when they exist locally.

use std::path::Path;

use sde_rbr::{parse_replay_ini, parse_replay_ini_str};

/// Run1: two vehicle recoveries, so it carries a `[RunkiSpots]` section.
const RUN1: &str = r"; RBR replay metadata file generated by NGPCarMenu plugin. Do not modify stage and car options

[Replay]
Type = RSF
Name = Gabiria-Legazpi 2004
TrackFolder = Maps\450-Gabiria-Legazpi
MapID = 450
MapLength = 6496
RallyType = Hotlap
RallyName =
CarModel = Mini JCW WRC
CarSlot = 5
SetupName = savedgames\Mini_JCW_WRC_ngp6\Tarmac Bumpy.lsp
FinishTimeSecs = 417.568512
AvgSpeedKPH = 56.004219
CarModelFolder = Cars\MINI_WRC01B
CarPhysicsFolder = rsfdata\cars\Mini_JCW_WRC_ngp6
DamageType = Realistic
TyreType = Tarmac Dry
WeatherType = Good
TimeOfDay = Morning
SkyCloudType = LightCloud
SkyType = Hazy
SurfaceWetness = Damp
SurfaceAge = New
TrackSetting = 450M_hazy_lightcloud
NGP = 7.5.779.508
RSF = 0.60.5074.0
RSFCarID = 101

[RunkiSpots]
Count = 2
R1Typ = C4H
R1Pos = 4342.6
R1Tim = 35.0
R2Typ = C4H
R2Pos = 5810.4
R2Tim = 35.0
";

/// Run2: clean run — note it omits `[RunkiSpots]` entirely rather than
/// writing `Count = 0`.
const RUN2: &str = r"; RBR replay metadata file generated by NGPCarMenu plugin. Do not modify stage and car options

[Replay]
Type = RSF
Name = Gabiria-Legazpi 2004
TrackFolder = Maps\450-Gabiria-Legazpi
MapID = 450
MapLength = 6496
RallyType = Hotlap
RallyName =
CarModel = Mini JCW WRC
CarSlot = 5
SetupName = savedgames\Mini_JCW_WRC_ngp6\my tarmac test.lsp
FinishTimeSecs = 282.276947
AvgSpeedKPH = 82.846298
CarModelFolder = Cars\MINI_WRC01B
CarPhysicsFolder = rsfdata\cars\Mini_JCW_WRC_ngp6
DamageType = Realistic
TyreType = Tarmac Dry
WeatherType = Good
TimeOfDay = Morning
SkyCloudType = LightCloud
SkyType = Hazy
SurfaceWetness = Damp
SurfaceAge = New
TrackSetting = 450M_hazy_lightcloud
NGP = 7.5.779.508
RSF = 0.60.5074.0
RSFCarID = 101
";

#[test]
fn parses_stage_car_and_conditions() {
    let info = parse_replay_ini_str(RUN1);

    assert_eq!(info.stage.name.as_deref(), Some("Gabiria-Legazpi 2004"));
    assert_eq!(info.stage.map_id, Some(450));
    assert_eq!(info.stage.length_m, Some(6496));
    assert_eq!(
        info.stage.track_folder.as_deref(),
        Some(r"Maps\450-Gabiria-Legazpi")
    );

    assert_eq!(info.car.model.as_deref(), Some("Mini JCW WRC"));
    assert_eq!(info.car.slot, Some(5));
    // The link from a run to the setup sheet it used.
    assert_eq!(
        info.car.setup_name.as_deref(),
        Some(r"savedgames\Mini_JCW_WRC_ngp6\Tarmac Bumpy.lsp")
    );
    assert_eq!(info.car.rsf_car_id, Some(101));

    assert_eq!(info.conditions.tyre_type.as_deref(), Some("Tarmac Dry"));
    assert_eq!(info.conditions.surface_wetness.as_deref(), Some("Damp"));
    assert_eq!(info.conditions.damage_type.as_deref(), Some("Realistic"));

    assert_eq!(info.versions.ngp.as_deref(), Some("7.5.779.508"));
    assert_eq!(info.versions.replay_type.as_deref(), Some("RSF"));

    // Written but blank: absent as a value, rather than `Some("")`.
    assert_eq!(info.result.rally_type.as_deref(), Some("Hotlap"));
    assert_eq!(info.result.rally_name, None);

    // Every key is modelled, so nothing should spill into `extra`.
    assert!(info.extra.is_empty(), "unmodelled keys: {:?}", info.extra);
}

#[test]
fn parses_recovery_spots() {
    let info = parse_replay_ini_str(RUN1);

    assert!(info.recovery_section_present);
    assert_eq!(info.recovery_spots.len(), 2);

    let first = &info.recovery_spots[0];
    assert_eq!(first.kind.as_deref(), Some("C4H"));
    assert_eq!(first.position_m, Some(4342.6));
    assert_eq!(first.penalty_secs, Some(35.0));
    assert_eq!(info.recovery_spots[1].position_m, Some(5810.4));

    assert!((info.total_penalty_secs() - 70.0).abs() < 1e-9);
}

#[test]
fn driving_time_strips_recovery_penalties() {
    // The whole point of modelling penalties: Run1's *scored* 417.6 s and
    // Run2's 282.3 s aren't comparable, but the driving times are — and
    // 347.57 s is what the corrected telemetry timebase spans.
    let run1 = parse_replay_ini_str(RUN1);
    assert!((run1.result.finish_time_secs.unwrap() - 417.568_512).abs() < 1e-9);
    assert!((run1.driving_time_secs().unwrap() - 347.568_512).abs() < 1e-9);

    let run2 = parse_replay_ini_str(RUN2);
    assert!((run2.driving_time_secs().unwrap() - 282.276_947).abs() < 1e-9);
}

#[test]
fn clean_run_has_no_recovery_section() {
    let info = parse_replay_ini_str(RUN2);

    assert!(!info.recovery_section_present);
    assert!(info.recovery_spots.is_empty());
    assert_eq!(info.total_penalty_secs(), 0.0);
    // Distinguishes the two runs' setups, which is what makes them a
    // meaningful A/B pair.
    assert_eq!(
        info.car.setup_name.as_deref(),
        Some(r"savedgames\Mini_JCW_WRC_ngp6\my tarmac test.lsp")
    );
}

#[test]
fn unmodelled_keys_are_preserved_in_extra() {
    // A newer RSF build adding a field must stay reachable without a code
    // change here.
    let text = "[Replay]\nMapID = 450\nSomeFutureField = 42\n";
    let info = parse_replay_ini_str(text);

    assert_eq!(info.stage.map_id, Some(450));
    assert_eq!(
        info.extra.get("somefuturefield").map(String::as_str),
        Some("42")
    );
}

#[test]
fn missing_and_malformed_fields_degrade_to_none() {
    // One bad field must not cost the caller the rest of the file.
    let text = "[Replay]\nName = Somewhere\nMapID = notanumber\nFinishTimeSecs = \n";
    let info = parse_replay_ini_str(text);

    assert_eq!(info.stage.name.as_deref(), Some("Somewhere"));
    assert_eq!(info.stage.map_id, None);
    assert_eq!(info.result.finish_time_secs, None);
    assert_eq!(info.driving_time_secs(), None);
}

#[test]
fn empty_input_yields_an_empty_but_valid_record() {
    let info = parse_replay_ini_str("");
    assert_eq!(info, sde_rbr::ReplayInfo::default());
}

#[test]
fn inflated_count_does_not_invent_empty_spots() {
    // `Count` is trusted only as far as the keys actually present agree.
    let text = "[RunkiSpots]\nCount = 5\nR1Pos = 100.0\nR1Tim = 35.0\n";
    let info = parse_replay_ini_str(text);
    assert_eq!(info.recovery_spots.len(), 1);
    assert_eq!(info.recovery_spots[0].position_m, Some(100.0));
}

/// Exercises the on-disk path against the real captures. Skipped when
/// `.sample-data/` isn't present (it's gitignored), so CI stays green
/// without it.
#[test]
fn parses_real_sample_data_when_present() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../../.sample-data/RBR/MINI JCW - Gabiria-Legazpi 2004");
    if !root.is_dir() {
        eprintln!("skipping: {} not present", root.display());
        return;
    }

    let cases = [
        (
            "Run1/replay/Anna_rsf_hotlap_Gabiria-Legazpi 2004_6_57.568_5.ini",
            2usize,
            417.568_512_f64,
        ),
        (
            "Run2/replay/Anna_rsf_hotlap_Gabiria-Legazpi 2004_4_42.276_5.ini",
            0,
            282.276_947,
        ),
    ];

    for (rel, spots, finish) in cases {
        let path = root.join(rel);
        let info = parse_replay_ini(&path)
            .unwrap_or_else(|e| panic!("failed to parse {}: {e}", path.display()));

        assert_eq!(info.stage.map_id, Some(450), "{rel}");
        assert_eq!(info.stage.length_m, Some(6496), "{rel}");
        assert_eq!(info.car.model.as_deref(), Some("Mini JCW WRC"), "{rel}");
        assert_eq!(info.recovery_spots.len(), spots, "{rel}");
        assert!(
            (info.result.finish_time_secs.unwrap() - finish).abs() < 1e-6,
            "{rel}"
        );
    }
}

#[test]
fn io_error_on_missing_file() {
    let err = parse_replay_ini(Path::new("/definitely/does/not/exist/nope.ini")).unwrap_err();
    assert!(matches!(err, sde_rbr::RbrError::Io { .. }), "got {err:?}");
}
